### PR TITLE
Fix misleading documentation of metal::arg

### LINKED ISSUE #94: Is `metal::arg` documented correctly (0-based vs. 1-based index)?
From the [explanation](https://github.com/brunocodutra/metal/blob/99e3857c5f069d553d4e5c07a33a0c7f53309578/include/metal/lambda/arg.hpp#L21) I expect a 0-based indexing, but the implementation uses 1-based indexing. Am I missing anything?

> ### Usage
> 
> For any non negative integral value `m`
> ```
> using result = metal::arg<m>;
> ```
> #### Returns: lambda
> #### Semantics:
> Equivalent to
> ```
> using result = metal::lambda<expr>;
> ```
> where `expr` is an Expression such that `expr<val_0, ..., val_m, ..., val_n-1>` yields `val_m`.
> ### Example
> ```
> IS_SAME(metal::invoke<metal::arg<1>, bool, char, long, float>, bool);
> IS_SAME(metal::invoke<metal::arg<2>, bool, char, long, float>, char);
> IS_SAME(metal::invoke<metal::arg<3>, bool, char, long, float>, long);
> IS_SAME(metal::invoke<metal::arg<4>, bool, char, long, float>, float);
> ```

### PR DESCRIPTION
**Pull request by brunocodutra**
Fixes #94

### CODE REVIEW

File: include/metal/lambda/arg.hpp [hunk 1]
```diff
@@ -19,7 +19,7 @@ namespace metal {
     /// A parametric \lambda that selects the n-th argument it is invoked with.
     ///
     /// ### Usage
-    /// For any non negative integral value `m`
+    /// For any non zero positive integral value `m`
```
Comment (ecrypa) [inline include/metal/lambda/arg.hpp]: I suggest to shorten this line to 

> For any positive integral value `m`

If you insist on being explicit here, then I prefer "nonzero" over "non zero".

File: include/metal/lambda/arg.hpp [hunk 2]
```diff
@@ -19,7 +19,7 @@ namespace metal {
     /// A parametric \lambda that selects the n-th argument it is invoked with.
```
Comment (ecrypa) [inline include/metal/lambda/arg.hpp]: I assume that you intentionally use n-th vs. (see below) `m`.

I think it is alright now, but I just want to make sure you did not miss it.

Comment (brunocodutra) [reply include/metal/lambda/arg.hpp]: I thought about changing it to `m-th`. Since it also caught your eye, I'll changing since I'm at it.

File: include/metal/lambda/arg.hpp (hunk 1 above)
Comment (brunocodutra) [reply include/metal/lambda/arg.hpp]: I like your rigor :)

File: include/metal/lambda/arg.hpp (hunk 2 above)
Comment (ecrypa) [reply include/metal/lambda/arg.hpp]: There are other occurences of `n`. The template-argument name is visible in the [documentation](http://brunocodutra.github.io/metal/group__lambda.html#ga5adc3e3a25b8ce55e4993fa719b85ce3). Anyway, let us not get lost in details here.

Comment (brunocodutra) [reply include/metal/lambda/arg.hpp]: Oh boy

Comment (brunocodutra) [reply include/metal/lambda/arg.hpp]: I guess at this point it's easier to revert this and rename the `n`s to `m`s.

Comment (ecrypa) [reply include/metal/lambda/arg.hpp]: I apologize for overcomplicating this.

What matters here is the 1-based vs. 0-based issue. Thanks for the quick clarification.

Comment (brunocodutra) [reply include/metal/lambda/arg.hpp]: Not at all - I do care about these little details and I'm glad you helped me get it right.
